### ISSUE TITLE
Suggestion of adding `abind` among required packages

### ISSUE THREAD

**Issue by alexgag11** [oloapinivad/MiLES#7]
Dear Paolo,

I would like to suggest to include the `abind` package among the required packages because even if the `installpack.R` file gives the message "All packages are present..." the execution fails due to the missing package `abind`. After installing that package, everything worked fine.

I should mention that I installed the required packages manually and perhaps installing them through your installation script would have installed the `abind` package as well.

Thanks.

Best,
Alessandro

**Comment by alexgag11** [comment]
I saw now that is planned for the next version. I close the issue since you are aware of the problem.

Best,
Alessandro

**Comment by oloapinivad** [comment]
Hi @alexgag11, unfortunately I am no longer maintaining this project, in the main this should be however fixed...
